version: '3'
services:
  app-prometheus-division2:
    image: app-prometheus-division2
    container_name: app-prometheus-division2
    ports:
      - 8000:8000
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus-divisoin2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    links:
      - app-prometheus-division2
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana-division2
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: always

